services:

  broker-1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: broker-1
    container_name: broker-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093,2@broker-2:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker-1:29092,CONTROLLER://broker-1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./scripts/workaround.sh:/tmp/workaround.sh
    command: "bash -c '/tmp/workaround.sh && /etc/confluent/docker/run'"
    healthcheck:
      test: echo srvr | nc broker-1 9092 || exit 1
      interval: 5s
      retries: 10

  broker-2:
    image: confluentinc/cp-kafka:7.3.2
    hostname: broker-2
    container_name: broker-2
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:29092,PLAINTEXT_HOST://localhost:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093,2@broker-2:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker-2:29092,CONTROLLER://broker-2:29093,PLAINTEXT_HOST://0.0.0.0:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./scripts/workaround.sh:/tmp/workaround.sh
    command: "bash -c '/tmp/workaround.sh && /etc/confluent/docker/run'"
    healthcheck:
      test: echo srvr | nc broker-2 9093 || exit 1
      interval: 5s
      retries: 10

  # broker-3:
  #   image: confluentinc/cp-kafka:7.3.2
  #   hostname: broker-3
  #   container_name: broker-3
  #   ports:
  #     - "9094:9094"
  #   environment:
  #     KAFKA_NODE_ID: 3
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  #     KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:29092,PLAINTEXT_HOST://localhost:9094'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     KAFKA_PROCESS_ROLES: 'broker'
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093,2@broker-2:29093'
  #     KAFKA_LISTENERS: 'PLAINTEXT://broker-3:29092,PLAINTEXT_HOST://0.0.0.0:9094'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #     KAFKA_CONTROLLER_LISTENER_NAMES: 'BROKER'
  #     KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  #   volumes:
  #     - ./scripts/workaround.sh:/tmp/workaround.sh
  #   command: "bash -c '/tmp/workaround.sh && /etc/confluent/docker/run'"
  #   healthcheck:
  #     test: echo srvr | nc broker-3 9094 || exit 1
  #     interval: 5s
  #     retries: 10

  # broker-4:
  #   image: confluentinc/cp-kafka:7.3.2
  #   hostname: broker-4
  #   container_name: broker-4
  #   ports:
  #     - "9095:9095"
  #   environment:
  #     KAFKA_NODE_ID: 4
  #     KAFKA_BROKER_ID: 4
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  #     KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-4:29092,PLAINTEXT_HOST://localhost:9095'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     KAFKA_PROCESS_ROLES: 'broker'
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093,2@broker-2:29093'
  #     KAFKA_LISTENERS: 'PLAINTEXT://broker-4:29092,PLAINTEXT_HOST://0.0.0.0:9095'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #     KAFKA_CONTROLLER_LISTENER_NAMES: 'BROKER'
  #     KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  #   volumes:
  #     - ./scripts/workaround.sh:/tmp/workaround.sh
  #   command: "bash -c '/tmp/workaround.sh && /etc/confluent/docker/run'"
  #   healthcheck:
  #     test: echo srvr | nc broker-4 9095 || exit 1
  #     interval: 5s
  #     retries: 10
